# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TournamentApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TournamentApp
  pod 'SDWebImage', '~> 5.0'
  pod 'Alamofire', '~> 5.2'
  pod 'AlamofireURLCache5'
  
end
